#!/usr/bin/python
# OpenTimestamps server
#
# Copyright (C) 2012 Peter Todd <pete@petertodd.org>
#
# This file is part of OpenTimestamps.
#
# OpenTimestamps is free software; you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published by the
# Free Software Foundation; either version 3 of the License, or (at your
# option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import sys
if sys.version_info[1] < 7:
    sys.exit("OpenTimestamps requires Python version 2.7.0 or newer. "\
             "(you have %d.%d.%d)"%sys.version_info[0:3])

import argparse
import cherrypy
import binascii
from opentimestamps.dag import *
from opentimestamps.serialize import json_deserialize

parser = argparse.ArgumentParser(description="OpenTimestamps client")
verbosity_group = parser.add_mutually_exclusive_group()
verbosity_group.add_argument("-q","--quiet",action="store_true",
                             help="be quiet")
verbosity_group.add_argument("-v","--verbose",action="store_true",
                             help="be verbose")

args = parser.parse_args()

class OpenTimestampsServer(object):
    @cherrypy.expose
    def index(self):
        return "Hello World!"

    @cherrypy.expose
    def submit(self):
        cl = cherrypy.request.headers['Content-Length']
        rawbody = cherrypy.request.body.read(int(cl))
        new_dagvertex = json_deserialize(rawbody)
        return 'submitted json is:\n%s' % new_dagvertex.json_serialize()

    @cherrypy.expose
    def hash(self,digest):
        return 'hash digest is %s' % digest

    @cherrypy.expose
    def path(self,digest,dstspec):
        return 'path from %s to %s' % (digest,dstspec)

cherrypy.quickstart(OpenTimestampsServer())
