#!/usr/bin/python
# Testing 
#
# Copyright (C) 2012 Peter Todd <pete@petertodd.org>
#
# This file is part of OpenTimestamps.
#
# OpenTimestamps is free software; you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published by the
# Free Software Foundation; either version 3 of the License, or (at your
# option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import json
from opentimestamps.dag import MemoryDag,Hash,Verify
from opentimestamps.serialization import json_serialize

dag = MemoryDag()

a = Hash(inputs=('hello world!',),dag=dag)
b = Hash(inputs=('goodbye world!',),dag=dag)
c = Hash(inputs=(a,b),dag=dag)

print(json.dumps(json_serialize(c),indent=4))
